name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck hadolint openjdk-17-jre-headless unzip
    - name: ShellCheck
      run: |
        shellcheck setup.sh keycloak_setup.sh tests/test_setup.sh tests/test_keycloak.sh
    - name: Lint Dockerfile
      run: |
        hadolint Dockerfile
    - name: Run tests
      run: |
        chmod +x setup.sh keycloak_setup.sh tests/test_setup.sh tests/test_dockerfile.sh tests/test_keycloak.sh
        bash tests/test_setup.sh
        bash tests/test_dockerfile.sh
        bash tests/test_keycloak.sh
